// <auto-generated />
namespace RoyalShop.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RevenuesStatisticSP : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RevenuesStatisticSP));
        
        string IMigrationMetadata.Id
        {
            get { return "201712141806467_RevenuesStatisticSP"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
